data:
  batch_size: 30
  embedding_dir: ./dataset/embeddings
  end_idx: 30
  info_dir: /data/planetzoo
  mesh_dir: ./dataset/simplified_meshes/
  out_dir: ./output
  retrieval_animal: dinasour
  start_idx: 0
  test_animal: common_warthog_juvenile
model:
  w_flow: 10000
  w_mask: 10000
  w_smooth: 1000000
  w_symm: 10000
seed: 2000
type: synthetic
