data:
  batch_size: 30
  embedding_dir: ./dataset/embeddings
  end_idx: 30
  info_dir: /projects/perception/datasets/animal_videos/version9/
  mesh_dir: ./dataset/simplified_meshes/
  out_dir: ./output
  retrieval_animal: babirusa_juvenile
  start_idx: 0
  test_animal: aardvark_male
model:
  w_flow: 1000000
  w_mask: 10000
  w_smooth: 1000000
  w_symm: 10000
seed: 2000
type: synthetic
